//Format 1
//Width: 1920 Pixels, Height: 1080 Pixels, Pixel Format: Blue, Green, Red, Reserved
pub const SCREEN_HEIGHT: usize = 1080; //PIXEL HEIGHT OF SCREEN
pub const SCREEN_WIDTH:  usize = 1920; //PIXEL WIDTH OF SCREEN
pub const FRAME_HEIGHT:  usize = 67;   //TEXT MODE HEIGHT OF CHARACTER FRAME
pub const FRAME_WIDTH:   usize = 120;  //TEXT MODE WIDTH OF CHARACTER FRAME
pub const PRINT_LINES:   usize = 250;  //TEXT MODE HEIGHT OF PRINT RESULT WINDOW IN MEMORY
pub const PRINT_HEIGHT:  usize = 62;   //TEXT MODE HEIGHT OF PRINT RESULT WINDOW ON SCREEN
pub const PRINT_WIDTH:   usize = 118;  //TEXT MODE WIDTH OF PRINT RESULT WINDOW
pub const PRINT_Y:       usize = 2;    //TEXT MODE VERTICAL POSITION OF PRINT RESULT WINDOW
pub const PRINT_X:       usize = 1;    //TEXT MODE HORIZONTAL POSITION OF PRINT RESULT WINDOW
pub const INPUT_LENGTH:  usize = 118;  //TEXT MODE HEIGHT OF INPUT WINDOW IN MEMORY
pub const INPUT_WIDTH:   usize = 118;  //TEXT MODE WIDTH OF INPUT WINDOW
pub const INPUT_Y:       usize = 65;   //TEXT MODE VERTICAL POSITION OF INPUT WINDOW
pub const INPUT_X:       usize = 1;    //TEXT MODE HORIZONTAL POSITION OF INPUT WINDOW